import { createElement } from 'lwc';
import ContactActivityRelatedList_LWC from 'c/contactActivityRelatedList_LWC';

describe('c-contact-activity-related-list-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-contact-activity-related-list-lwc', {
            is: ContactActivityRelatedList_LWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});